# Reference: https://github.com/Renato66/auto-label
# name: Labeling new issue
# # The event that triggers the workflow
# on:
#   issues:
#     types: ['opened']
# jobs:
#   build:
#     # The machine each job should run
#     runs-on: ubuntu-latest
#     # The tasks each job should run
#     steps:
#       - uses: Renato66/auto-label@v2
#         with:
#           repo-token: ${{ secrets.GITHUB_TOKEN }}
#           ignore-comments: true
#           labels-synonyms: '{"bug":["error","need fix","not working"],"enhancement":["upgrade"],"question":["help"]}'
#           labels-not-allowed: '["good first issue"]'
#           default-labels: '["LGMSOC21"]'

name: Default

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Label Syncer
      uses: micnncim/action-label-syncer@v1.3.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      with:
        manifest: .github/labels.json
        prune: false
